### ISSUE TITLE
npm install necessary for module?

### ISSUE THREAD

**Issue by schlomm** [matteodanelli/MMM-cryptocurrency#94]
Thanks for this great module!
Unfortunately it took me a while to get it up and running. After a few hours I performed and "npm install" in the module directory.
Is this actually needed?

After the process was done, MagicMirror started correctly. Before I got the following messages using ````pm2 log MagicMirror````

```
pi@raspberrypi:~/MagicMirror $ pm2 log MagicMirror
[TAILING] Tailing last 15 lines for [MagicMirror] process (change the value with --lines option)
/home/pi/.pm2/logs/MagicMirror-out.log last 15 lines:
0|MagicMir | [10.08.2021 14:24.11.604] [LOG]   No helper found for module: clock.
0|MagicMir | [10.08.2021 14:24.11.762] [LOG]   Initializing new module helper ...
0|MagicMir | [10.08.2021 14:24.11.763] [LOG]   Module helper loaded: calendar
0|MagicMir | [10.08.2021 14:24.11.764] [LOG]   No helper found for module: compliments.
0|MagicMir | [10.08.2021 14:24.11.765] [LOG]   No helper found for module: weather.
0|MagicMir | [10.08.2021 14:24.11.771] [LOG]   Loading module helpers ...
0|MagicMir | [10.08.2021 14:24.11.772] [LOG]   No helper found for module: alert.
0|MagicMir | [10.08.2021 14:24.11.773] [LOG]   Initializing new module helper ...
0|MagicMir | [10.08.2021 14:24.11.774] [LOG]   Module helper loaded: updatenotification
0|MagicMir | [10.08.2021 14:24.11.775] [LOG]   No helper found for module: clock.
0|MagicMir | [10.08.2021 14:24.11.775] [LOG]   Initializing new module helper ...
0|MagicMir | [10.08.2021 14:24.11.776] [LOG]   Module helper loaded: calendar
0|MagicMir | [10.08.2021 14:24.11.778] [LOG]   No helper found for module: compliments.
0|MagicMir | [10.08.2021 14:24.11.779] [LOG]   No helper found for module: weather.
0|MagicMir | [10.08.2021 14:24.12.094] [LOG]   Launching application.

/home/pi/.pm2/logs/MagicMirror-error.log last 15 lines:
0|MagicMir |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-cryptocurrency/node_helper.js:2:15)
0|MagicMir |     at Module._compile (internal/modules/cjs/loader.js:1152:30)
0|MagicMir |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10) {
0|MagicMir |   code: 'MODULE_NOT_FOUND',
0|MagicMir |   requireStack: [
0|MagicMir |     '/home/pi/MagicMirror/modules/MMM-cryptocurrency/node_helper.js',
0|MagicMir |     '/home/pi/MagicMirror/js/app.js',
0|MagicMir |     '/home/pi/MagicMirror/js/electron.js',
0|MagicMir |     '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
0|MagicMir |     undefined
0|MagicMir |   ]
0|MagicMir | }
0|MagicMir | [10.08.2021 14:24.11.793] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | [10.08.2021 14:24.11.793] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMir | /home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
```

In case the ````npm install```` is needed (and it's not caused by any (for me unknown) issue), it might be worth it to mention it in the installation documentation.

**Comment by matteodanelli** [comment]
It should not needed anymore.
If you have time, please check. Feel free to reopen in case it's required.
